export const TAKEAWAY_DETAILS_TYPE = {
    IMAGE_GALLERY: 'image_gallery',
    IMAGE_GALLERY_SUCCESS: 'image_gallery_success',
    HYGIENE_RATING: 'HYGIENE_RATING',
    HYGIENE_RATING_SUCCESS: 'HYGIENE_RATING_SUCCESS',
    GET_STORE_CONFIG: 'GET_STORE_SETTINGS',
    GET_STORE_CONFIG_SUCCESS: 'GET_STORE_SETTINGS_SUCCESS'
};
