export const PROFILE_TYPE = {
    GET_PROFILE: 'get_profile',
    UPDATE_PROFILE: 'update_profile',
    GET_PROFILE_SUCCESS: 'get_profile_success',
    EXPORT_DATA: 'export_data',
    DELETE_ACCOUNT: 'delete_account',
    POST_SEND_OTP: 'post_send_otp',
    VERIFY_OTP: 'verify_otp',
    UPDATE_CONSENT_PROFILE_RESPONSE: 'update_consent_profile_response',
    SHOW_HIDE_VERIFY_OTP: 'show_hide_verify_otp',
    OTP_LENGTH: 'otp_length',
    GET_CARD_DETAILS: 'get_card_details',
    GET_CARD_DETAILS_SUCCESS: 'get_card_details_success',
    DELETE_CARD_DETAILS: 'delete_card_details',
    VERIFY_OTP_ERROR_MSG: 'verify_otp_error_msg',
    OTP_LIMIT_EXCEEDED: 'otp_limit_exceeded',
    RESET_VERIFY_OTP_VALUES: 'reset_verify_otp_values',
    DUPLICATE_PHONE_NUMBER: 'duplicate_phone_number',
    UPDATE_PROFILE_API_STATUS: 'update_profile_api_status',
    PROFILE_SHOW_PROGRESS: 'profile_show_progress',
    UPDATE_REFERRAL_CODE: 'update_referral_code',
    POST_REFERRAL_CODE: 'post_referral_code',
    UPDATE_RECENT_PBL: 'update_recent_pbl',
    RESET_PBL: 'reset_pbl'
};
