import { isFoodHubApp } from '../Utils/helpers';
import { getDarkColor } from 'appmodules/BaseModule/Helper';
import Config from 'react-native-config';

const Colors = {
    white: '#ffffff',
    lightGrey: '#d3d3d3',
    grey: '#f7f7f7',
    greyHeaderText: '#c0c0c0',
    lightTextColorGrey: '#3E4A59',
    textGreyColor: '#555555',
    backgroundGrey: '#F2F2F2',
    dividerGrey: '#EEEEEE',
    lighterGrey: '#e6e6e6',
    black: '#333333',
    suvaGrey: '#888888',
    primaryColor: Config.PRIMARY_APP_COLOR,
    secondary_color: Config.SECONDARY_COLOR,
    foodHubDarkGreen: isFoodHubApp() ? '#37724A' : getDarkColor(Config.PRIMARY_APP_COLOR),
    whiteSmoke: '#F7F7F7',
    persianRed: '#D12F2F',
    ashColor: '#CCCCCC',
    lightYellow: '#FFF7D7',
    blue: '#017aff',
    eclipse: '#3a3a3a',
    lightBlue: '#198ebc',
    lightGrayShade: '#F2F2F2',
    lightBrown: '#F49A38',
    lightYellowShade: '#FFE36E',
    limeColor: '#B0D657',
    ashGrey: '#efeff5',
    lightGold: '#F5A623',
    gold: '#F1C40F',
    greyShadow: '#999999',
    crayola: '#323643',
    lightRed: '#ffefef',
    gallery: '#EEEEEE',
    silver: '#BBBBBB',
    aliceBlue: '#FAFBFD',
    suluGreen: '#D1EA8C',
    warning: '#F0AD4E',
    carrotOrange: '#F47925',
    mediumGray: '#ADADAD',
    gunmetal: '#242A37',
    shadowGrey: '#000000',
    icon_purple: '#9D7BD2',
    icon_green: '#A3C05F',
    textBlue: '#198EBC',
    ratingYellow: '#F7D823',
    ratingGreen: '#387C2E',
    mongoose: '#AF9E80',
    tacha: '#D4C76D',
    lightBlack: '#31394D',
    dark_grey: '#212121',
    statusBarColor: '#0E1C24',
    tabGrey: '#AAAAAA',
    lightWhite: '#EDEDF3',
    transparent: 'transparent',
    underlineColor: '#CACACA',
    yellow: '#FFFF00',
    rating_yellow: '#FFCE00',
    rating_grey: '#888888',
    gondola: '#363636',
    malachite: '#14CB53',
    middleGrey: '#777777',
    veryLightWhite: '#F5F5F5',
    WhiteSmoke: '#EAEAEA',
    darkBlack: '#000',
    viking: '#42ADBB',
    PaleOyster: '#9E8D6E',
    PurpleHeart: '#5827B7',
    neroGrey: '#252525',
    DarkOrange: '#E67D3B',
    BittersweetRed: '#FF665A',
    paleBlue: '#65bcd8',
    chipBlack: '#151515',
    chipBg: '#EFEFEF',
    violet: '#9881CD',
    bigFoodieOrange: '#ED7656',
    ToolBarPrimaryColor: '#ffffff', //toolbar color.
    primaryTextColor: '#333333', // primary text color(kinda black color) across the App,
    secondaryTextColor: '#888888', // secondary text color (grey color) for the app, like labels.
    notificationCountBgColor: '#E67D3B', // background color for notification count on toolbar.
    sideMenuBackgroundColor: '#EAEAEA', // background color of the navigation drawer.
    sideMenuHeaderBackgroundColor: '#ffffff', // background color of the navigation drawer's header.
    palegreen: '#DBDD6D', //default color of hygenic rating widget
    lightOrange: '#AF9E80',
    shadowBlack: 'rgba(0,0,0,0.7)',
    mildBlue: '#036AFF',
    mildGrey: '#CFCFCF',
    selectedItemColor: '#5D3CAD',
    yellowGreen: '#DDF29F',
    mildlightgrey: '#f8f4f4',
    basketGradientGreenStart: '#3C8730',
    tabBarActionColor: '#158DB0',
    orange: '#FFA500',
    orangeBg: '#F8F5EF',
    modifier: '#E5BA76',
    freeOption: '#FD7F06',
    offGrey: '#CCCCCC',
    express_light: '#F47925',
    express_dark: '#DE6512',
    lightGreyText: '#7d7d7d',
    mildYellow: '#AE9E80',
    rating_color: '#D82927',
    tundora: '#444444',
    tip_bg_Black: '#323334',
    mid_grey: '#9B9B9C',
    paleYellow: '#F8F5EE',
    discountColor: '#EA332F',
    lightRatingYellow: '#FFCC00',
    lightRatingGrey: '#E7E7E7',
    takeawayGreen: '#5BAE75',
    thinBlack: '#1E2432',
    imageBorder: '#DDDDDD',
    mildPersianRed: '#D53B3B',
    mildRed: '#FC7056',
    bottomBar: '#60ac74',
    blackLight: '#111111',
    lightAsh: '#7A7A7A',
    darkOrange: '#EF901C',
    turquoiseGreen: '#009A90',
    liteLavender: '#745CA8',
    purple: '#2A0D3A',
    liteYellow: '#FEBE1B',
    paleOrange: '#FBD99A',
    lighterOrange: '#F5B261',
    palePink: '#ECD8EB',
    vividPink: '#D4AFD3',
    droverOrange: '#FFEB9A',
    dandelionOrange: '#FFD361',
    paleAqua: '#ADE8EB',
    sprayBlue: '#75CCD2',
    whiteLilac: '#EEE6F3',
    fogPurple: '#D8C9E3',
    labelRed: '#ED515B',
    paleRed: '#FBDDDF'
};

export default Colors;
