import { Dimensions } from 'react-native';

export const SCREEN_NAME = {
    HOME_SCREEN: 'home_screen'
};
export const VIEW_ID = {
    STEP1: 'Step1',
    LOCATE: 'Locate',
    SELECT: 'Select',
    PAY: 'Pay',
    RELISH: 'Relish',
    RECENT_TAKEAWAY_LIST: 'recent_takeaway_list',
    CARD_VIEW: 'card_view',
    CARD_TAKEAWAY_NAME: 'card_takeaway_name',
    ROW_VIEW: 'row_view',
    RATING_TEXT: 'rating_text',
    STEP_NO_TEXT: 'step_no_text',
    CARD_TITLE: 'card_title',
    ENJOY_FOOD_VIEW: 'enjoy_food_view',
    ENJOY_FOOD_TEXT: 'enjoy_food_text',
    REVIEWS_TEXT: 'reviews_text',
    RECENT_ORDERS_TEXT: 'recent_orders_text',
    CAROUSEL_IMAGE: 'carousel_image',
    CAROUSEL_IMAGE_TEXT: 'carousel_image_text',
    CURRENCY_SYMBOL: 'currency_symbol',
    RENDER_CARDS: 'render_cards',
    RECENT_ORDER_TEXT_VIEW: 'recent_orders_text_view',
    RECENT_ORDERS: 'recent_orders',
    ORDER_STATUS_CONTAINER: 'order_status_container',
    ORDER_STATUS_TEXT: 'order_status_text',
    CLOCK_VIEW: 'clock_view',
    DELIVERY_TEXT_CONTAINER: 'delivery_text_container',
    DELIVERY: 'delivery',
    COLLECTION: 'collection',
    DEFAULT_TIME: 'default_time',
    RECENT_TAKEAWAY: 'recent_takeaway',
    RECENT_TAKEAWAY_TITLE_TEXT: 'recent_takeaway_title_text',
    RATING_ROW_VIEW: 'ratings_row_view',
    SEARCH_BAR_VIEW: 'search_bar_view',
    SEARCH_BAR_INPUT_VIEW: 'search_bar_input_view',
    SEARCH_BAR_CONTAINER: 'search_bar_container',
    GPS_ICON: 'gps_icon',
    FIND_BUTTON: 'find_button',
    FIND_TEXT: 'find_text',
    CLOSE_ICON: 'close_icon',
    CLOSE_ICON_TOUCHID: 'close_icon_id',
    ORDER_STATUS_VIEW: 'order_status_view',
    VIEW_MENU_BTN: 'view_menu_btn',
    OUR_RECOMMENDATION_VIEW_ALL: 'our_recommendation_view_all_text',
    WEBVIEW_MODAL: 'web_view_modal',
    WEBVIEW_SCREEN_BASE_COMPONENT: 'webview_Screen_base_component',
    WEBVIEW_COMPONENT: 'webview_component',
    RECENT_ORDER_VIEW: 'recent_order_view',
    RECENT_ORDER_STORE_NAME: 'recent_order_store_name',
    RECENT_ORDER_TIMER_VIEW: 'recent_order_timer_view',
    RECENT_ORDER_TOTAL_PRICE: 'recent_order_total_price',
    ORDER_SUMMARY_ITEMS: 'order_summary_items',
    ORDER_PLACED_DATE: 'order_placed_date',
    ORDER_STORE_NAME: 'order_store_name',
    ORDER_TYPE: 'order_type',
    REORDER_CLICKABLE_VIEW: 'reorder_clickable_view',
    ORDER_HISTORY_VIEW_ALL: 'order_history_view_all',
    VIEW_ALL: 'view_all',
    CART_ICON: 'cart_icon',
    CART_ICON_VIEW: 'cart_icon_view',
    CART_BUTTON: 'cart_button',
    ITEM_COUNT: 'item_count',
    CUSTOM_TOTALSAVINGS_IMAGE_VIEW: 'custom_totalsavings_image_view',
    CUSTOM_ORDERNOW_IMAGE_VIEW: 'custom_ordernow_image_view',
    CUSTOM_DELIVERY_IMAGE_VIEW: 'custome_delivery_imageview',
    WORNG_ICON: 'worng_icon',
    MAP_ICON: 'map',
    TOTAL_SAVING_AMOUNT: 'total_savings_amount',
    NO_TAKEAWAY_IMAGE: 'no_takeaway_image',
    ORDER_TIMER_TEXT: 'order_timer_text',
    NO_TAKEAWAY_BUTTON: 'no_takeaway_button',
    OK: 'ok',
    ORDER_DATE_AND_TIME_TEXT: 'order_date_and_time_text',
    ORDER_STATUS_IMAGE: 'order_status_image',
    REORDER_TOTAL_TEXT: 'reorder_total_text',
    REORDER_TOTAL: 'reorder_total'
};

export const HOME_CONSTANTS = {
    POSTCODE_TIMEOUT: 1000,
    SEARCH_ADDRESS: 'address',
    ENTER_POSTCODE: 'Enter your Postcode',
    ENTER_AREA: 'Enter your Area'
};

export const carousalHeight = (Dimensions.get('window').height * 39) / 100;
