import { ORDER_TYPE } from 'appmodules/BaseModule/BaseConstants';
import { addresses, delivery_address, preOrderDates, savedCardDetails } from '../data';
import { PAYMENT_TYPE } from 'appmodules/QuickCheckoutModule/Utils/QuickCheckoutConstants';

export const cartItemsArray = [
    {
        id: 28013101,
        quantity: 3,
        quantityType: 'ADD',
        item: {
            id: 28013101,
            host: 'd-111.t2scdn.com',
            item_addon_cat: '0',
            name: 'Pepsi Max - 1.5L',
            description: '',
            information: null,
            price: '1.99',
            subcat: 5893858,
            image: '',
            aws_image: '',
            image_backup: '',
            addon_type: '',
            monday: 0,
            tuesday: 1,
            wednesday: 1,
            thursday: 1,
            friday: 1,
            saturday: 1,
            sunday: 1,
            delivery: 1,
            collection: 1,
            show_online: 1,
            background_color: '0000ff',
            font_color: 'ffffff',
            pos: 0,
            offer: 'NONE',
            btn_name: '',
            mip_id: 0,
            coupon_allowed: 1,
            collection_discount_allowed: 1,
            online_discount_allowed: 1,
            item_code: '',
            added: '2021-08-02 07:00:38',
            user_id: '',
            page: '',
            modified: '2021-08-02 07:02:54',
            modified_by: '',
            modified_page: '',
            vat: '0',
            exclude_free: 1,
            second_language_name: '',
            second_language_description: '',
            printer: 0,
            section: 0,
            is_print_label: '0',
            is_vat_included: '0',
            food_type: 'NONE',
            sections: null,
            half_and_half_status: 0,
            half_and_half_charges: null,
            is_schedule: 1,
            region_tax_id: null,
            schedule: []
        },
        fromBasket: false,
        fromFreeItems: false,
        fromBasketRecommendation: false
    },
    {
        id: 28013102,
        quantity: 1,
        quantityType: 'ADD',
        item: {
            id: 28013102,
            host: 'd-111.t2scdn.com',
            item_addon_cat: '0',
            name: 'Tango - 1.5L',
            description: '',
            information: null,
            price: '1.99',
            subcat: 5893858,
            image: '',
            aws_image: '',
            image_backup: '',
            addon_type: '',
            monday: 0,
            tuesday: 1,
            wednesday: 1,
            thursday: 1,
            friday: 1,
            saturday: 1,
            sunday: 1,
            delivery: 1,
            collection: 1,
            show_online: 1,
            background_color: '0000ff',
            font_color: 'ffffff',
            pos: 0,
            offer: 'NONE',
            btn_name: '',
            mip_id: 0,
            coupon_allowed: 1,
            collection_discount_allowed: 1,
            online_discount_allowed: 1,
            item_code: '',
            added: '2021-08-02 07:00:38',
            user_id: '',
            page: '',
            modified: '2021-08-02 07:02:54',
            modified_by: '',
            modified_page: '',
            vat: '0',
            exclude_free: 1,
            second_language_name: '',
            second_language_description: '',
            printer: 0,
            section: 0,
            is_print_label: '0',
            is_vat_included: '0',
            food_type: 'NONE',
            sections: null,
            half_and_half_status: 0,
            half_and_half_charges: null,
            is_schedule: 1,
            region_tax_id: null,
            schedule: []
        },
        fromBasket: false,
        fromFreeItems: false,
        fromBasketRecommendation: false
    },
    {
        id: 28013094,
        quantity: 1,
        quantityType: 'ADD',
        item: {
            id: 28013094,
            host: 'd-111.t2scdn.com',
            item_addon_cat: '0',
            name: 'Fruit Shoot',
            description: '',
            information: null,
            price: '0.99',
            subcat: 5893858,
            image: '',
            aws_image: '',
            image_backup: '',
            addon_type: '',
            monday: 0,
            tuesday: 1,
            wednesday: 1,
            thursday: 1,
            friday: 1,
            saturday: 1,
            sunday: 1,
            delivery: 1,
            collection: 1,
            show_online: 1,
            background_color: '0000ff',
            font_color: 'ffffff',
            pos: 0,
            offer: 'NONE',
            btn_name: '',
            mip_id: 0,
            coupon_allowed: 1,
            collection_discount_allowed: 1,
            online_discount_allowed: 1,
            item_code: '',
            added: '2021-08-02 07:00:38',
            user_id: '',
            page: '',
            modified: '2021-08-02 07:02:54',
            modified_by: '',
            modified_page: '',
            vat: '0',
            exclude_free: 1,
            second_language_name: '',
            second_language_description: '',
            printer: 0,
            section: 0,
            is_print_label: '0',
            is_vat_included: '0',
            food_type: 'NONE',
            sections: null,
            half_and_half_status: 0,
            half_and_half_charges: null,
            is_schedule: 1,
            region_tax_id: null,
            schedule: []
        },
        fromBasket: false,
        fromFreeItems: false,
        fromBasketRecommendation: false
    },
    {
        id: 28013096,
        quantity: 1,
        quantityType: 'ADD',
        item: {
            id: 28013096,
            host: 'd-111.t2scdn.com',
            item_addon_cat: '0',
            name: 'Water - 0.5L',
            description: '',
            information: null,
            price: '0.99',
            subcat: 5893858,
            image: '',
            aws_image: '',
            image_backup: '',
            addon_type: '',
            monday: 0,
            tuesday: 1,
            wednesday: 1,
            thursday: 1,
            friday: 1,
            saturday: 1,
            sunday: 1,
            delivery: 1,
            collection: 1,
            show_online: 1,
            background_color: '0000ff',
            font_color: 'ffffff',
            pos: 0,
            offer: 'NONE',
            btn_name: '',
            mip_id: 0,
            coupon_allowed: 1,
            collection_discount_allowed: 1,
            online_discount_allowed: 1,
            item_code: '',
            added: '2021-08-02 07:00:38',
            user_id: '',
            page: '',
            modified: '2021-08-02 07:02:54',
            modified_by: '',
            modified_page: '',
            vat: '0',
            exclude_free: 1,
            second_language_name: '',
            second_language_description: '',
            printer: 0,
            section: 0,
            is_print_label: '0',
            is_vat_included: '0',
            food_type: 'NONE',
            sections: null,
            half_and_half_status: 0,
            half_and_half_charges: null,
            is_schedule: 1,
            region_tax_id: null,
            schedule: []
        },
        fromBasket: false,
        fromFreeItems: false,
        fromBasketRecommendation: false
    }
];

export const cartItem = {
    id: 28013096,
    quantity: 2,
    quantityType: 'ADD',
    item: {
        id: 28013096,
        host: 'd-111.t2scdn.com',
        item_addon_cat: '0',
        name: 'Water - 0.5L',
        description: '',
        information: null,
        price: '0.99',
        subcat: 5893858,
        image: '',
        aws_image: '',
        image_backup: '',
        addon_type: '',
        monday: 0,
        tuesday: 1,
        wednesday: 1,
        thursday: 1,
        friday: 1,
        saturday: 1,
        sunday: 1,
        delivery: 1,
        collection: 1,
        show_online: 1,
        background_color: '0000ff',
        font_color: 'ffffff',
        pos: 0,
        offer: 'BOGOF',
        btn_name: '',
        mip_id: 0,
        coupon_allowed: 0,
        collection_discount_allowed: 1,
        online_discount_allowed: 1,
        item_code: '',
        added: '2021-08-02 07:00:38',
        user_id: '',
        page: '',
        modified: '2021-08-02 07:02:54',
        modified_by: '',
        modified_page: '',
        vat: '0',
        exclude_free: 1,
        second_language_name: '',
        second_language_description: '',
        printer: 0,
        section: 0,
        is_print_label: '0',
        is_vat_included: '0',
        food_type: 'NONE',
        sections: null,
        half_and_half_status: 0,
        half_and_half_charges: null,
        is_schedule: 1,
        region_tax_id: null,
        schedule: []
    },
    fromBasket: false,
    fromFreeItems: false,
    fromBasketRecommendation: false
};

export const newCartItem = {
    id: 28013097,
    quantity: 2,
    quantityType: 'ADD',
    item: {
        id: 28013097,
        host: 'd-111.t2scdn.com',
        item_addon_cat: '0',
        name: 'Water - 0.5L',
        description: '',
        information: null,
        price: '0.99',
        subcat: 5893858,
        image: '',
        aws_image: '',
        image_backup: '',
        addon_type: '',
        monday: 0,
        tuesday: 1,
        wednesday: 1,
        thursday: 1,
        friday: 1,
        saturday: 1,
        sunday: 1,
        delivery: 1,
        collection: 1,
        show_online: 1,
        background_color: '0000ff',
        font_color: 'ffffff',
        pos: 0,
        offer: 'BOGOH',
        btn_name: '',
        mip_id: 0,
        coupon_allowed: 1,
        collection_discount_allowed: 1,
        online_discount_allowed: 1,
        item_code: '',
        added: '2021-08-02 07:00:38',
        user_id: '',
        page: '',
        modified: '2021-08-02 07:02:54',
        modified_by: '',
        modified_page: '',
        vat: '0',
        exclude_free: 1,
        second_language_name: '',
        second_language_description: '',
        printer: 0,
        section: 0,
        is_print_label: '0',
        is_vat_included: '0',
        food_type: 'NONE',
        sections: null,
        half_and_half_status: 0,
        half_and_half_charges: null,
        is_schedule: 1,
        region_tax_id: null,
        schedule: []
    },
    fromBasket: true,
    fromFreeItems: false,
    fromBasketRecommendation: false
};

export const resourceIDs = [
    {
        resourceID: 812637755,
        id: 28013101,
        offer: 'NONE',
        addOns: [],
        item: {
            id: 28013101,
            host: 'd-111.t2scdn.com',
            item_addon_cat: '0',
            name: 'Pepsi Max - 1.5L',
            description: '',
            information: null,
            price: '1.99',
            subcat: 5893858,
            image: '',
            aws_image: '',
            image_backup: '',
            addon_type: '',
            monday: 0,
            tuesday: 1,
            wednesday: 1,
            thursday: 1,
            friday: 1,
            saturday: 1,
            sunday: 1,
            delivery: 1,
            collection: 1,
            show_online: 1,
            background_color: '0000ff',
            font_color: 'ffffff',
            pos: 0,
            offer: 'NONE',
            btn_name: '',
            mip_id: 0,
            coupon_allowed: 1,
            collection_discount_allowed: 1,
            online_discount_allowed: 1,
            item_code: '',
            added: '2021-08-02 07:00:38',
            user_id: '',
            page: '',
            modified: '2021-08-02 07:02:54',
            modified_by: '',
            modified_page: '',
            vat: '0',
            exclude_free: 1,
            second_language_name: '',
            second_language_description: '',
            printer: 0,
            section: 0,
            is_print_label: '0',
            is_vat_included: '0',
            food_type: 'NONE',
            sections: null,
            half_and_half_status: 0,
            half_and_half_charges: null,
            is_schedule: 1,
            region_tax_id: null,
            schedule: []
        }
    },
    {
        resourceID: 812637759,
        id: 28013102,
        offer: 'NONE',
        addOns: [],
        item: {
            id: 28013102,
            host: 'd-111.t2scdn.com',
            item_addon_cat: '0',
            name: 'Tango - 1.5L',
            description: '',
            information: null,
            price: '1.99',
            subcat: 5893858,
            image: '',
            aws_image: '',
            image_backup: '',
            addon_type: '',
            monday: 0,
            tuesday: 1,
            wednesday: 1,
            thursday: 1,
            friday: 1,
            saturday: 1,
            sunday: 1,
            delivery: 1,
            collection: 1,
            show_online: 1,
            background_color: '0000ff',
            font_color: 'ffffff',
            pos: 0,
            offer: 'NONE',
            btn_name: '',
            mip_id: 0,
            coupon_allowed: 1,
            collection_discount_allowed: 1,
            online_discount_allowed: 1,
            item_code: '',
            added: '2021-08-02 07:00:38',
            user_id: '',
            page: '',
            modified: '2021-08-02 07:02:54',
            modified_by: '',
            modified_page: '',
            vat: '0',
            exclude_free: 1,
            second_language_name: '',
            second_language_description: '',
            printer: 0,
            section: 0,
            is_print_label: '0',
            is_vat_included: '0',
            food_type: 'NONE',
            sections: null,
            half_and_half_status: 0,
            half_and_half_charges: null,
            is_schedule: 1,
            region_tax_id: null,
            schedule: []
        }
    },
    {
        resourceID: 812637786,
        id: 28013094,
        offer: 'NONE',
        addOns: [],
        item: {
            id: 28013094,
            host: 'd-111.t2scdn.com',
            item_addon_cat: '0',
            name: 'Fruit Shoot',
            description: '',
            information: null,
            price: '0.99',
            subcat: 5893858,
            image: '',
            aws_image: '',
            image_backup: '',
            addon_type: '',
            monday: 0,
            tuesday: 1,
            wednesday: 1,
            thursday: 1,
            friday: 1,
            saturday: 1,
            sunday: 1,
            delivery: 1,
            collection: 1,
            show_online: 1,
            background_color: '0000ff',
            font_color: 'ffffff',
            pos: 0,
            offer: 'NONE',
            btn_name: '',
            mip_id: 0,
            coupon_allowed: 1,
            collection_discount_allowed: 1,
            online_discount_allowed: 1,
            item_code: '',
            added: '2021-08-02 07:00:38',
            user_id: '',
            page: '',
            modified: '2021-08-02 07:02:54',
            modified_by: '',
            modified_page: '',
            vat: '0',
            exclude_free: 1,
            second_language_name: '',
            second_language_description: '',
            printer: 0,
            section: 0,
            is_print_label: '0',
            is_vat_included: '0',
            food_type: 'NONE',
            sections: null,
            half_and_half_status: 0,
            half_and_half_charges: null,
            is_schedule: 1,
            region_tax_id: null,
            schedule: []
        }
    },
    {
        resourceID: 812638129,
        id: 28013096,
        offer: 'NONE',
        addOns: [],
        item: {
            id: 28013096,
            host: 'd-111.t2scdn.com',
            item_addon_cat: '0',
            name: 'Water - 0.5L',
            description: '',
            information: null,
            price: '0.99',
            subcat: 5893858,
            image: '',
            aws_image: '',
            image_backup: '',
            addon_type: '',
            monday: 0,
            tuesday: 1,
            wednesday: 1,
            thursday: 1,
            friday: 1,
            saturday: 1,
            sunday: 1,
            delivery: 1,
            collection: 1,
            show_online: 1,
            background_color: '0000ff',
            font_color: 'ffffff',
            pos: 0,
            offer: 'NONE',
            btn_name: '',
            mip_id: 0,
            coupon_allowed: 1,
            collection_discount_allowed: 1,
            online_discount_allowed: 1,
            item_code: '',
            added: '2021-08-02 07:00:38',
            user_id: '',
            page: '',
            modified: '2021-08-02 07:02:54',
            modified_by: '',
            modified_page: '',
            vat: '0',
            exclude_free: 1,
            second_language_name: '',
            second_language_description: '',
            printer: 0,
            section: 0,
            is_print_label: '0',
            is_vat_included: '0',
            food_type: 'NONE',
            sections: null,
            half_and_half_status: 0,
            half_and_half_charges: null,
            is_schedule: 1,
            region_tax_id: null,
            schedule: []
        }
    }
];

export const reorderResponse = [
    {
        host: 'web-1-uk.t2scdn.com',
        item_id: 326592172,
        name: 'All Salad',
        second_language_name: '',
        type: '',
        price: '0.00',
        menu_price: '0.00',
        offer: 'NONE',
        offline_id: null,
        quantity: 1,
        version: 2,
        item_addon_id: 203854125,
        tax_percentage: null,
        modifier: 'NONE'
    },
    {
        host: 'web-1-uk.t2scdn.com',
        item_id: 326592172,
        name: 'Lettuce',
        second_language_name: '',
        type: '',
        price: '0.00',
        menu_price: '0.00',
        offer: 'NONE',
        offline_id: null,
        quantity: 1,
        version: 2,
        item_addon_id: 203854188,
        tax_percentage: null,
        modifier: 'NONE'
    },
    {
        host: 'web-1-uk.t2scdn.com',
        item_id: 326592172,
        name: 'Onion',
        second_language_name: '',
        type: '',
        price: '0.00',
        menu_price: '0.00',
        offer: 'NONE',
        offline_id: null,
        quantity: 1,
        version: 2,
        item_addon_id: 203854239,
        tax_percentage: null,
        modifier: 'NONE'
    }
];

export const orderPayload = [
    {
        id: 326592172,
        item_id: 15068564,
        subcat: 3264296,
        quantity: 1,
        name: 'Small Egg Burger With Chips And Doner Meat',
        second_language_name: '',
        price: '6.70',
        menu_price: '6.70',
        coupon_allowed: 0,
        addons: [
            {
                id: 500407877,
                quantity: 1,
                name: 'All Salad',
                second_language_name: '',
                price: '0.00',
                menu_price: '0.00',
                item_addon_id: 203854125
            },
            {
                id: 500407878,
                quantity: 1,
                name: 'Lettuce',
                second_language_name: '',
                price: '0.00',
                menu_price: '0.00',
                item_addon_id: 203854188
            },
            {
                id: 500407879,
                quantity: 1,
                name: 'Onion',
                second_language_name: '',
                price: '0.00',
                menu_price: '0.00',
                item_addon_id: 203854239
            }
        ],
        free: false,
        offer: 'NONE',
        position: null,
        sequence: 1,
        bogoFree: false,
        totalPrice: '6.70'
    }
];

export const reOrderHandleItem = {
    addOnItems: [
        {
            addOns: [
                { id: 203854125, modifier: 'NONE', name: 'All Salad', price: '0.00', second_language_name: '' },
                { id: 203854188, modifier: 'NONE', name: 'Lettuce', price: '0.00', second_language_name: '' },
                { id: 203854239, modifier: 'NONE', name: 'Onion', price: '0.00', second_language_name: '' }
            ],
            item: { id: 15068564 }
        }
    ],
    cart: [
        {
            id: 15068564,
            item: {
                addons: [
                    {
                        id: 500407877,
                        item_addon_id: 203854125,
                        menu_price: '0.00',
                        name: 'All Salad',
                        price: '0.00',
                        quantity: 1,
                        second_language_name: ''
                    },
                    {
                        id: 500407878,
                        item_addon_id: 203854188,
                        menu_price: '0.00',
                        name: 'Lettuce',
                        price: '0.00',
                        quantity: 1,
                        second_language_name: ''
                    },
                    {
                        id: 500407879,
                        item_addon_id: 203854239,
                        menu_price: '0.00',
                        name: 'Onion',
                        price: '0.00',
                        quantity: 1,
                        second_language_name: ''
                    }
                ],
                bogoFree: false,
                coupon_allowed: 0,
                free: false,
                id: 326592172,
                item_id: 15068564,
                menu_price: '6.70',
                name: 'Small Egg Burger With Chips And Doner Meat',
                offer: 'NONE',
                position: null,
                price: '6.70',
                quantity: 1,
                second_language_name: '',
                sequence: 1,
                subcat: 3264296,
                totalPrice: '6.70'
            },
            quantity: 1
        }
    ],
    resourceIDs: [
        {
            addOns: [
                { id: 203854125, modifier: 'NONE', name: 'All Salad', price: '0.00', second_language_name: '' },
                { id: 203854188, modifier: 'NONE', name: 'Lettuce', price: '0.00', second_language_name: '' },
                { id: 203854239, modifier: 'NONE', name: 'Onion', price: '0.00', second_language_name: '' }
            ],
            id: 15068564,
            item: {
                addons: [
                    {
                        id: 500407877,
                        item_addon_id: 203854125,
                        menu_price: '0.00',
                        name: 'All Salad',
                        price: '0.00',
                        quantity: 1,
                        second_language_name: ''
                    },
                    {
                        id: 500407878,
                        item_addon_id: 203854188,
                        menu_price: '0.00',
                        name: 'Lettuce',
                        price: '0.00',
                        quantity: 1,
                        second_language_name: ''
                    },
                    {
                        id: 500407879,
                        item_addon_id: 203854239,
                        menu_price: '0.00',
                        name: 'Onion',
                        price: '0.00',
                        quantity: 1,
                        second_language_name: ''
                    }
                ],
                bogoFree: false,
                coupon_allowed: 0,
                free: false,
                id: 326592172,
                item_id: 15068564,
                menu_price: '6.70',
                name: 'Small Egg Burger With Chips And Doner Meat',
                offer: 'NONE',
                position: null,
                price: '6.70',
                quantity: 1,
                second_language_name: '',
                sequence: 1,
                subcat: 3264296,
                totalPrice: '6.70'
            },
            offer: 'NONE',
            resourceID: 326592172
        }
    ],
    sequence: 1
};

export const remove_resource_id = {
    payload: {
        action: {
            addOns: undefined,
            fromBasket: true,
            fromBasketRecommendation: false,
            fromFreeItems: false,
            id: 15460937,
            item: [Object],
            quantity: 0,
            quantityType: 'MINUS',
            repeatAddOnType: undefined,
            type: 'add_remove_item_to_basket'
        },
        resourceID: 326592574
    },
    type: 'remove_resource_id'
};

export const props = {
    orderType: ORDER_TYPE.COLLECTION,
    takeAwayAddress: '1241  6 6',
    addressResponse: addresses,
    isCollectionAvailable: false,
    isDeliveryAvailable: false,
    selectedOrderType: ORDER_TYPE.COLLECTION,
    preOrderCollectionDates: preOrderDates,
    preOrderDeliveryDates: preOrderDates,
    selectedPaymentMode: PAYMENT_TYPE.CASH,
    subTotal: {
        label: 'Sub Total',
        value: '105.80'
    },
    onlineDiscount: {
        label: '30% Online Discount',
        value: '31.74',
        message: '<message_value>% Online Discount',
        message_value: 30
    },
    collectionDiscount: {
        label: '20% Collection Discount',
        value: '4.18',
        message: '<message_value> % Collection Discount',
        message_value: 20
    },
    couponSummary: {
        label: 'Discount (Coupon TEST)',
        code: 'TEST',
        value: '34.00',
        message: '<message_value> Discount (Coupon <placeholder>)',
        message_value: '',
        placeholder: ' TEST'
    },
    total: {
        label: 'Total',
        value: '74.06'
    }
};
export const delivery_props = {
    orderType: ORDER_TYPE.DELIVERY,
    takeAwayAddress: '16  12B,  Moorland Road,  Stoke-on-Trent,  ST6 1DT',
    deliveryAddress: delivery_address,
    addressResponse: addresses,
    currency: '£',
    walletBalance: '1.50',
    savedCardDetails: savedCardDetails,
    user_selected_card_id: 90719,
    isCollectionAvailable: true,
    isDeliveryAvailable: true,
    selectedOrderType: ORDER_TYPE.DELIVERY,
    preOrderCollectionDates: preOrderDates,
    preOrderDeliveryDates: preOrderDates,
    selectedPaymentMode: PAYMENT_TYPE.CARD,
    subTotal: {
        label: 'Sub Total',
        value: '5.70'
    },
    vat: {
        label: 'VAT Charges (12%)',
        value: '0.68',
        message: '<message_value> Charges (<placeholder>)',
        message_value: 'VAT',
        placeholder: 12
    },
    carryBag: {
        label: '1x Carry Bags',
        value: '0.50',
        message: '<message_value>x Carry Bags',
        message_value: 1
    },
    total: {
        label: 'Total',
        value: '8.88'
    },
    deliveryCharge: {
        label: 'Delivery Charge',
        value: '2.00'
    },
    adminFee: {
        label: 'Service Charge',
        value: '0.50'
    },
    driverTips: {
        label: 'Driver Tip',
        value: '2.00'
    }
};
export const empty_props = {
    orderType: null,
    takeAwayAddress: '',
    deliveryAddress: null,
    addressResponse: null,
    isCollectionAvailable: true,
    isDeliveryAvailable: true,
    selectedOrderType: null,
    preOrderCollectionDates: '',
    preOrderDeliveryDates: '',
    subTotal: undefined,
    serviceCharge: undefined,
    vat: undefined,
    adminFee: undefined,
    onlineDiscount: undefined,
    collectionDiscount: undefined,
    couponSummary: undefined,
    carryBag: undefined,
    redeemAmount: undefined,
    total: undefined,
    payment: undefined
};

export const formApiDataObject = {
    userID: 99007,
    deviceName: 'iPhone 11 Pro Max',
    orderType: 'delivery',
    preOrderDate: '',
    deliveryAddress: {
        id: 50340504,
        customer_id: 99007,
        house_number: '12',
        flat: '',
        address_line1: 'Susdf',
        address_line2: 'Rjkrjhsjf',
        postcode: 'AA1 1AA',
        area: 'moorsland',
        landmark: '',
        shop_name: null,
        label: null,
        instructions: null,
        latitude: '37.7858214',
        longitude: '-122.4064015',
        is_primary: 'NO',
        created_at: '2021-07-19 12:42:26',
        updated_at: '2021-07-19 12:42:26',
        deleted_at: null
    },
    contactFreeDelivery: false,
    profileResponse: {
        id: 99007,
        first_name: 'Subash',
        last_name: 'Muthu',
        phone: '07677184808',
        landline: '',
        email: 'subash@foodhub.com',
        dob: '0000-00-00',
        gender: null,
        is_subscribed_sms: 'YES',
        is_subscribed_email: 'NO',
        is_confirmed_email: 'NO',
        is_subscribed_cookie: 'NO',
        total_addresses: 0,
        total_payment_information: 0,
        total_stores: 1,
        version: 1,
        created_at: '2021-04-26 16:09:29',
        updated_at: '2021-06-07 12:24:13',
        deleted_at: null,
        api_token: '8f00f1e1b809834ec56c777a6d550123',
        is_subscribed_notification: 'NO',
        subscription: false,
        remember_payment: 'YES',
        saved_card: true,
        loyalty_point_available: 0,
        has_password: true,
        customer_joining_date: '2021-04-27 06:21:13'
    },
    pushNotificationToken:
        'deehwJ9aDEQ4uMJZSZbbV3:APA91bHY3k8JLfA-b-SGZCPAv-9isfheirsPrSvU1dSlphQ1Y6nuA8ytJWgx86KFhEx3zfDyfKAS30ftZ0VH8WDafObDE7iGWrSd6ZHxYXk2Hkd4SwuP8ZPTbNAB1pwETWJXUEvxgYIV',
    orderComments: '',
    paymentMode: 'PARTIAL_PAYMENT'
};

export const formApiAction = {
    type: 'update_basket',
    updateType: 'view',
    allergyInfo: ''
};

export const updateCouponAction = {
    type: 'update_basket',
    updateType: 'coupon',
    coupon: 'TEST'
};

export const basketResponse = {
    errors: null,
    warnings: null,
    validation: null,
    currency: 'GBP',
    currency_symbol: '£',
    type: 'to',
    customer_id: null,
    free_gift: true,
    buy_one_get_one_free: false,
    buy_one_get_one_half: false,
    comments: null,
    contactless: false,
    pre_order_time: '0000-00-00 00:00:00',
    universal_coupon: true,
    coupon_code: '',
    item: [
        {
            id: 326596530,
            item_id: 15068606,
            subcat: 3264308,
            quantity: 1,
            name: '5GH',
            second_language_name: '',
            price: '17.0000',
            menu_price: '17.00',
            coupon_allowed: 0,
            addons: [],
            free: false,
            offer: 'NONE',
            position: null,
            sequence: 1,
            bogoFree: false
        }
    ],
    sub_total: {
        label: 'Sub Total',
        value: '17.00'
    },
    restaurant_service_charge: {
        label: '0% Restaurant Charge',
        value: '0.00',
        message: '<message_value> Restaurant Charge',
        message_value: '0% '
    },
    admin_fee: {
        label: 'Service charge',
        value: '0.45'
    },
    total: {
        label: 'Total',
        value: '17.45'
    }
};

export const handleAddonPayload = [
    {
        item: {
            id: 27244861,
            host: 'holeinthewallburslem.co.uk',
            item_addon_cat: '16007422',
            name: 'Full Monty Breakfast With 2 Oatcake',
            description: '',
            information: null,
            price: '4.95',
            subcat: 5727156,
            image: '',
            aws_image: '',
            image_backup: '',
            addon_type: '',
            monday: 1,
            tuesday: 1,
            wednesday: 1,
            thursday: 1,
            friday: 1,
            saturday: 1,
            sunday: 1,
            delivery: 1,
            collection: 1,
            show_online: 1,
            background_color: '0000ff',
            font_color: 'ffffff',
            pos: 0,
            offer: 'NONE',
            btn_name: '',
            mip_id: 0,
            coupon_allowed: 1,
            collection_discount_allowed: 1,
            online_discount_allowed: 1,
            item_code: '',
            added: '2021-06-25 15:49:01',
            user_id: '',
            page: '',
            modified: '2021-08-07 10:54:25',
            modified_by: '',
            modified_page: '',
            vat: '0',
            exclude_free: 1,
            second_language_name: '',
            second_language_description: '',
            printer: 0,
            section: 0,
            is_print_label: '0',
            is_vat_included: '0',
            food_type: 'NONE',
            sections: null,
            half_and_half_status: 0,
            half_and_half_charges: null,
            is_schedule: 1,
            region_tax_id: null,
            schedule: []
        },
        addOns: [
            {
                id: 276828219,
                modifier: 'NONE',
                name: '1 Bacon',
                price: '0.65',
                second_language_name: ''
            }
        ]
    }
];

export const menuResponseWithFree = [
    {
        id: 1815161,
        host: 'qa4.t2scdn.com',
        name: 'Free',
        pos: 5,
        pos_back: 8,
        pos_receipt: 0,
        background_color: '0000FF',
        font_color: 'ffffff',
        shrink: 1,
        hidden: '0',
        collection: 1,
        delivery: 1,
        mip_id: 0,
        monday: 1,
        tuesday: 1,
        wednesday: 1,
        thursday: 1,
        friday: 1,
        saturday: 1,
        sunday: 1,
        coupon_allowed: 1,
        collection_discount_allowed: 1,
        online_discount_allowed: 1,
        added: '2021-08-03 08:43:03',
        exclude_free: 1,
        second_language_name: '',
        hidden_fix: 'NO',
        printer: 0,
        section: 0,
        food_type_id: null,
        is_print_label: '0',
        updated_at: '2021-08-03 08:43:03',
        food_type: null,
        sections: null,
        created_by: null,
        show_online: 1,
        is_vat_included: '1',
        is_schedule: 0,
        region_tax_id: null,
        schedule: [],
        subcat: [
            {
                id: 3413999,
                host: 'qa4.t2scdn.com',
                name: 'Free',
                addon_type: 0,
                subcat_addon_cat: 0,
                description: '',
                image: '',
                aws_image: '',
                image_backup: '',
                category: 1815161,
                addon: '',
                background_color: '41A3C5',
                font_color: 'ffffff',
                pos: 1,
                pos_back: 0,
                delivery: 1,
                collection: 1,
                show_online: 1,
                menu_inputter_id: 7,
                monday: 1,
                tuesday: 1,
                wednesday: 1,
                thursday: 1,
                friday: 1,
                saturday: 1,
                sunday: 1,
                coupon_allowed: 1,
                collection_discount_allowed: 1,
                online_discount_allowed: 1,
                added: '2021-08-03 08:43:03',
                user_id: '',
                page: '',
                modified: '2021-08-03 08:43:03',
                modified_by: '',
                modified_page: '',
                offer_all: 'NONE',
                exclude_free: 1,
                second_language_name: '',
                second_language_description: '',
                food_type: 'NONE',
                sections: null,
                is_vat_included: '1',
                is_print_label: '0',
                additional_charges: '0.00',
                is_schedule: 0,
                region_tax_id: null,
                schedule: [],
                item: [
                    {
                        id: 15517508,
                        host: 'qa4.t2scdn.com',
                        item_addon_cat: '0',
                        name: 'Coke Free Or Discounts',
                        description: '',
                        information: null,
                        price: '0.00',
                        subcat: 3413999,
                        image:
                            'https://t2s-staging-nativepoc.s3.eu-west-1.amazonaws.com/private/d41d8cd98f00b204e9800998ecf8427e/jpg/1627968408.jpg',
                        aws_image: '',
                        image_backup: '',
                        addon_type: '',
                        monday: 1,
                        tuesday: 1,
                        wednesday: 1,
                        thursday: 1,
                        friday: 1,
                        saturday: 1,
                        sunday: 1,
                        delivery: 1,
                        collection: 1,
                        show_online: 1,
                        background_color: '0000ff',
                        font_color: 'ffffff',
                        pos: 1,
                        offer: 'NONE',
                        btn_name: '',
                        mip_id: 7,
                        coupon_allowed: 1,
                        collection_discount_allowed: 1,
                        online_discount_allowed: 1,
                        item_code: '',
                        added: '2021-08-03 08:43:03',
                        user_id: '',
                        page: '',
                        modified: '2021-08-03 08:43:03',
                        modified_by: '',
                        modified_page: '',
                        vat: '0',
                        exclude_free: 1,
                        second_language_name: '',
                        second_language_description: '',
                        printer: 0,
                        section: 0,
                        is_print_label: '0',
                        is_vat_included: '0',
                        food_type: 'NONE',
                        sections: null,
                        half_and_half_status: 0,
                        half_and_half_charges: null,
                        is_schedule: 0,
                        region_tax_id: null,
                        schedule: []
                    }
                ]
            }
        ]
    }
];

export const repeatAddonData = [
    {
        resourceID: 818262182,
        id: 28175865,
        offer: 'NONE',
        addOns: [
            {
                id: 283630780,
                modifier: 'NONE',
                name: 'Chicken',
                price: '1.50',
                second_language_name: null
            },
            {
                id: 283630781,
                modifier: 'NONE',
                name: 'Ham',
                price: '1.50',
                second_language_name: null
            },
            {
                id: 283630782,
                modifier: 'NONE',
                name: 'Mozzarella Cheese',
                price: '1.50',
                second_language_name: null
            }
        ],
        item: {
            id: 28175865,
            host: 'f8live.sy2.com',
            item_addon_cat: '16569602',
            name: '16" Funghi Pizza',
            description: '',
            information: null,
            price: '13.50',
            subcat: 5928572,
            image: '',
            aws_image: '',
            image_backup: '',
            addon_type: '',
            monday: 1,
            tuesday: 1,
            wednesday: 1,
            thursday: 1,
            friday: 1,
            saturday: 1,
            sunday: 1,
            delivery: 1,
            collection: 1,
            show_online: 1,
            background_color: '0000ff',
            font_color: 'ffffff',
            pos: 3,
            offer: 'NONE',
            btn_name: '',
            mip_id: 0,
            coupon_allowed: 1,
            collection_discount_allowed: 1,
            online_discount_allowed: 1,
            item_code: null,
            added: '2021-08-10 07:27:36',
            user_id: '',
            page: '',
            modified: '2021-08-10 07:27:36',
            modified_by: '',
            modified_page: '',
            vat: '0',
            exclude_free: 1,
            second_language_name: null,
            second_language_description: null,
            printer: 0,
            section: 0,
            is_print_label: '0',
            is_vat_included: '0',
            food_type: 'NONE',
            sections: null,
            half_and_half_status: 0,
            half_and_half_charges: null,
            is_schedule: 1,
            region_tax_id: null,
            is_image_approved: '0',
            category_id: 2601892,
            schedule: []
        }
    }
];

export const recommendationArray = [
    {
        source_item: 15502902,
        recommendation: 28013102
    },
    {
        source_item: 15502902,
        recommendation: 28013101
    },
    {
        source_item: 15502850,
        recommendation: 15502845
    }
];
