export const SESSION_AUTH_TYPE = {
    CLIENT: 'CLIENT',
    CONSUMER: 'CONSUMER'
};
export const SESSION_EXPIRE_BEFORE_CHECK = 60;
export const DEFAULT_TOKEN_TYPE = 'Bearer';
export const ERROR_CODE = {
    UNAUTHORIZED_CLIENT: 4011,
    UNAUTHORIZED_ACCESS: 4012,
    CUSTOMER_NOT_REGISTERED: 4013,
    REQUEST_PARAM_MISSING: 4014,
    ACCOUNT_NOT_VERIFIED: 4015,
    INVALID_USER_NUMBER: 60027,
    OTP_ATTEMPTS_FAILURE: 60003,
    DUPLICATE: 422,
    VALIDATION: 400
};
